blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/tanish0320/Setu/discussions
    about: Ask questions, share ideas, and engage with other contributors.
